### ISSUE TITLE
Stabilize rendering strategy, including device-specific bugs

### ISSUE THREAD

**Issue by cdata** [GoogleWebComponents/model-viewer#616]
This is a meta-issue to track work for the 0.5.0 release related to stabilizing our rendering strategy and cleaning up device specific bugs. Related issues include (in rough order or prioritization):

## Primary work threads

In order of priority:

 - [x] 🚧 #648 Select / author fidelity tests to judge rendering fidelity of PMREM overhaul
 - [x] ⭐️ #647 Use consistent, cross-device compatible single rendering path for IBL
 - [x] 🚧 #396 Deprecate stage-light-intensity / change default to 0
 - [x] ⭐️ #181 Ability to blur environment map when applied to skybox
 - [x] ⭐️ #650 Improved default material for loaded glTFs

## Adjacent issues

In no particular order:

- [x] 🐛 #649 PMREM appears to be generated twice
- [x] 🐛 #574 Environment map generation fails on some devices
- [x] 🐛 #587 Rendering inconsistencies with fine detailed normals + roughness
- [x] 🐛 #601 LDR environment maps without PMREM do not light nonmetallic, rough objects at all
- [x] 🐛 #528 HDR environment maps are not interpolated
- [x] 🐛 #632 Undesirable moiré effect apparent in some cases
- [x] 🚧 #521 Change fidelity tests to use new default IBL

**Comment by cdata** [comment]
Epic effort here by @elalish great work!
